# 世界地图中英文字典
# -*- coding: utf-8 -*-
nameMap = {
           'China':'中国',
           'Denmark':'丹麦',
           'Israel':'以色列',
           'Iraq':'伊拉克',
           'Russia':'俄罗斯',
           'Croatia':'克罗地亚',
           'Iceland':'冰岛',
           'Canada':'加拿大',
           'Ireland':'爱尔兰',
           'Macedonia':'北马其顿',
           'India':'印度',
           'Ecuador':'厄瓜多尔',
           'Colombia':'哥伦比亚',
           'San Marino':'圣马力诺',
           'Egypt':'埃及',
           'Mexico':'墨西哥',
           'Austria':'奥地利',
           'Nigeria':'尼日利亚',
           'Nepal':'尼泊尔',
           'Pakistan':'巴基斯坦',
           'Bahrain':'巴林',
           'Brazil':'巴西',
           'Greece':'希腊',
           'Germany':'德国',
           'Norway':'挪威',
           'Monaco':'摩纳哥',
           'Sri Lanka':'斯里兰卡',
           'New Zealand':'新西兰',
           'Cambodia':'柬埔寨',
           'Georgia':'格鲁吉亚',
           'Belgium':'比利时',
           'France':'法国',
           'Thailand':'泰国',
           'Australia':'澳大利亚',
           'Estonia':'爱沙尼亚',
           'Sweden':'瑞典',
           'Switzerland':'瑞士',
           'Belarus':'白俄罗斯',
           'Kuwait':'科威特',
           'Côte d\'Ivoire':'科特迪瓦',
           'Lithuania':'立陶宛',
           'Romania':'罗马尼亚',
           'Finland':'芬兰',
           'United Kingdom':'英国',
           'Netherlands':'荷兰',
           'Philippines':'菲律宾',
           'Spain':'西班牙',
           'Vietnam':'越南',
           'Azerbaijan':'阿塞拜疆',
           'Afghanistan':'阿富汗',
           'Algeria':'阿尔及利亚',
           'Oman':'阿曼',
           'United Arab Emirates':'阿联酋',
           'Malaysia':'马来西亚',
           'Lebanon':'黎巴嫩',
           'Korea':'韩国',
           'Iran':'伊朗',
           'Italy':'意大利',
           'Singapore':'新加坡',
           'Japan':'日本',
           'Princess Diamond':'钻石公主号',
           'United States':'美国',
           'Czech Rep.':'捷克',
           'Indonesia':'印度尼西亚',
           'Qatar':'卡塔尔',
           'Dominican Rep.':'多米尼加',
           'Luxembourg':'卢森堡',
           'Portugal':'葡萄牙',
           'Armenia':'亚美尼亚',
           'Jordan':'约旦',
           'Andorra':'安道尔',
           'Senegal':'塞内加尔',
           'Saudi Arabia':'沙特阿拉伯',
           'Tunisia':'突尼斯',
           'Latvia':'拉脱维亚',
           'Morocco':'摩洛哥',
           'Ukraine':'乌克兰',
           'Argentina':'阿根廷',
           'Chile':'智利',
           'Poland':'波兰',
           'Hungary':'匈牙利',
           'Slovenia':'斯洛文尼亚',
           'Bosnia and Herz.':'波黑',
           'South Africa':'南非',
           'French Guiana':'法属圭亚那',
           'Palestine':'巴勒斯坦',
           'Bhutan':'不丹',
           'Cameroon':'喀麦隆',
           'Vatican':'梵蒂冈',
           'Serbia':'塞尔维亚',
           'Slovakia':'斯洛伐克',
           'Peru':'秘鲁',
           'Liechtenstein':'列支敦士登公国',
           'Togo':'多哥',
           'Costa Rica':'哥斯达黎加',
           'Malta':'马耳他',
           'Maldives':'马尔代夫',
           'Paraguay':'巴拉圭',
           'Moldova':'摩尔多瓦',
           'Brunei':'文莱',
           'Bangladesh':'孟加拉国',
           'Bulgaria':'保加利亚',
           'Albania':'阿尔巴尼亚',
           'Cyprus':'塞浦路斯',
           'N. Cyprus':'北塞浦路斯',
           'Burkina Faso':'布基纳法索',
           'Mongolia':'蒙古国',
           'Panama':'巴拿马',
           'Turkey':'土耳其',
           'Jamaica':'牙买加',
           'Bolivia':'玻利维亚',
           'Honduras':'洪都拉斯',
           'Guyana':'圭亚那',
           'Cuba':'古巴',
           'Ghana':'加纳',
           'Gabon':'加蓬',
           'Trinidad and Tobago':'特立尼达和多巴哥',
           'Kenya':'肯尼亚',
           'Kazakhstan':'哈萨克斯坦',
           'Ethiopia':'埃塞俄比亚',
           'Guinea':'几内亚',
           'Eq. Guinea':'赤道几内亚',
           'Sudan':'苏丹',
           'Venezuela':'委内瑞拉',
           'Uruguay':'乌拉圭',
           'Guatemala':'危地马拉',
           'Antigua and Barb.':'安提瓜和巴布达',
           'Suriname':'苏里南',
           'Mauritania':'毛里塔尼亚',
           'Swaziland':'斯威士兰',
           'Rwanda':'卢旺达',
           'Namibia':'纳米比亚',
           'Equatorial Guinea':'赤道几内亚',
           'Seychelles':'塞舌尔',
           'Central African Rep.':'中非共和国',
           'Uzbekistan':'乌兹别克斯坦',
           'Congo':'刚果（布）',
           'Dem. Rep. Congo':'刚果（金）',
           'Bahamas':'巴哈马',
           'Liberia':'利比里亚',
           'Tanzania':'坦桑尼亚',
           'Somalia':'索马里',
           'Benin':'贝宁',
           'Libya':'利比亚',
           'Greenland':'格陵兰',
           'Montenegro':'黑山',
           'Gambia':'冈比亚',
           'Barbados':'巴巴多斯',
           'Kyrgyzstan':'吉尔吉斯斯坦',
           'Zambia':'赞比亚',
           'Mauritius':'毛里求斯',
           'Fiji':'斐济',
           'Nicaragua':'尼加拉瓜',
           'El Salvador':'萨尔瓦多',
           'Chad':'乍得',
           'Niger':'尼日尔',
           'Haiti':'海地',
           'Cape Verde':'佛得角',
           'Madagascar':'马达加斯加',
           'Zimbabwe':'津巴布韦',
           'Papua New Guinea':'巴布亚新几内亚',
           'Timor-Leste':'东帝汶',
           'Uganda':'乌干达',
           'Eritrea':'厄立特里亚',
           'Mozambique':'莫桑比克',
           'Syria':'叙利亚',
           'Dominica':'多米尼克',
           'Ruby Princess':'红宝石公主号',
           'Myanmar':'缅甸',
           'Yukon Territory':'育空地区',
           'Belize':'伯利兹',
           'Lao PDR':'老挝',
           'U.S. Virgin Is':'美属维尔京群岛',
           'St.Pierre and Miquelon':'圣皮埃尔和密克隆岛',
           'Bermuda':'百慕大群岛',
           'Puerto Rico':'波多黎各',
           'Montserrat':'蒙特塞拉特岛',
           'Saint Lucia':'圣卢西亚',
           'Grenada':'格林纳达',
           'Turks and Caicos Is.':'特克斯和凯科斯群岛',
           'Cayman Is.':'开曼群岛',
           'Curacao':'库拉索',
           'Tonga':'汤加',
           'Niue':'纽埃',
           'Samoa':'萨摩亚',
           'American Samoa':'美属萨摩亚',
           'Fr.Polynesia':'法属波利尼西亚',
           'Aland':'奥兰群岛',
           'Yemen':'也门',
           'Angola':'安哥拉',
           'Botswana':'博茨瓦纳',
           'Lesotho':'莱索托',
           'Malawi':'马拉维',
           'S. Sudan':'南苏丹',
           'Saint Helena':'圣赫勒拿岛',
           'Guinea-Bissau':'几内亚比绍',
           'Mali':'马里',
           'Fr. S. Antarctic Lands':'法属南极领地',
           'Heard I. and Macdoanld Is':'赫德岛和麦克唐纳岛',
           'Turkmenistan':'土库曼斯坦',
           'Tajikistan':'塔吉克斯坦',
           'Siachen Glacier':'锡亚琴冰川',
           'W. Sahara':'萨阿拉',
           'Dem. Rep. Korea':'朝鲜',
           'N. Mariana Is.':'北马里亚那群岛',
           'Guam':'关岛',
           'Palau':'帕劳',
           'Micronesia':'密克罗尼西亚',
           'Vanuatu':'瓦努阿图',
           'New Caledonia':'新喀里多尼亚',
           'Solomon Is.':'所罗门群岛',
           'Falkland Is.':'马尔维纳斯群岛',
           'S. Geo and S. Sandw. Is.':'南乔治亚和南桑德威奇群岛',
           'The Federation of Saint Kitts and Nevis':'圣基茨和尼维斯',
           'Anguilla':'安圭拉',
           'Aruba':'阿鲁巴',
           'Gibraltar':'直布罗陀',
           'Martinique':'马提尼克岛'
        }
